name: yolov11_test
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.8
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8
  - pip
  - pip:
      - ultralytics==8.3.228
      - pywavelets>=1.4.1
      - grad-cam>=1.5.5
      - opencv-python
      - matplotlib
      - pandas
      - seaborn
      - tqdm
      - scikit-learn
      - tensorboard